import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <title>Restaurant Website Templates | Swigo - Empowering Your Food Business | DexignZone</title>

        {/* <!-- Meta --> */}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="author" content="DexignZone" />
        <meta name="robots" content="" />
        <meta name="keywords"
          content="restaurant, restaurant website templates, restaurant template, food, restro, hotel, bootstrap 5, bootstrap, html, frontend, swigo, responsive template, shop, cart, menu, taste, blog, service, cook, customers, website, hungry, shop cart, fast food, table booking, website templates for restaurants, food website templates" />
        <meta name="description"
          content="Boost your food business with Swigo's restaurant website templates. Our professionally designed templates cater specifically to the needs of restaurants, offering visually stunning and functional designs. Choose from a variety of food website templates that are perfect for showcasing your menu, promoting your services, and attracting hungry customers. Partner with DexignZone to create an impressive online presence for your restaurant. Start driving more traffic and growing your business today." />
        <meta property="og:title" content="Swigo - Empowering Your Restaurant Website Templates | DexignZone" />
        <meta property="og:description"
          content="Boost your food business with Swigo's restaurant website templates. Our professionally designed templates cater specifically to the needs of restaurants, offering visually stunning and functional designs. Choose from a variety of food website templates that are perfect for showcasing your menu, promoting your services, and attracting hungry customers. Partner with DexignZone to create an impressive online presence for your restaurant. Start driving more traffic and growing your business today." />
        <meta property="og:image" content="https://swigo.dexignzone.com/xhtml/social-home.png" />
        <meta name="format-detection" content="telephone=no" />

        {/* <!-- Mobile Specific --> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Favicon icon --> */}
        <link rel="icon" type="image/png" href="../assets/images/favicon.png" />

        {/* <!-- Stylesheet --> */}
        <link href="../assets/vendor/animate/animate.css" rel="stylesheet" />
        <link href="../assets/vendor/magnific-popup/magnific-popup.min.css" rel="stylesheet" />
        <link href="../assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
        <link href="../assets/vendor/bootstrap-select/css/bootstrap-select.min.css" rel="stylesheet" />
        <link href="../assets/vendor/tempus-dominus/css/tempus-dominus.min.css" rel="stylesheet" />

        {/* <!-- Custom Stylesheet --> */}
        <link rel="stylesheet" href="../assets/vendor/rangeslider/rangeslider.css" />
        <link rel="stylesheet" href="../assets/vendor/switcher/switcher.css" />
        <link rel="stylesheet" href="../assets/css/style.css" />
        <link className="skin" rel="stylesheet" href="../assets/css/skin/skin-1.css" />

        {/* <!-- Google Fonts --> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Poppins:ital,wght@0,100;0,200;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"></link>
      </Head>

      <Main />
      <NextScript />

      {/* <!-- JAVASCRIPT FILES ========================================= --> */}
      <script src="../assets/js/jquery.min.js"></script>{/* <!-- JQUERY.MIN JS --> */}
      <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      {/* <!-- BOOTSTRAP.MIN JS --> */}
      <script src="../assets/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
      {/* <!-- BOOTSTRAP SELEECT --> */}
      <script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
      {/* <!-- MAGNIFIC POPUP JS --> */}
      <script src="../assets/vendor/counter/waypoints-min.js"></script>
      {/* <!-- WAYPOINTS JS --> */}
      <script src="../assets/vendor/wow/wow.js"></script>
      {/* <!-- WOW JS --> */}
      <script src="../assets/vendor/counter/counterup.min.js"></script>
      {/* <!-- COUNTERUP JS --> */}
      <script src="../assets/vendor/swiper/swiper-bundle.min.js"></script>
      {/* <!-- OWL-CAROUSEL --> */}
      <script src="../assets/vendor/popper/popper.js"></script>
      {/* <!-- Popper --> */}
      <script src="../assets/vendor/tempus-dominus/js/tempus-dominus.min.js"></script>
      {/* <!-- Tempus Dominus --> */}
      <script src="../assets/vendor/tilt/tilt.jquery.min.js"></script>
      {/* <!-- TILT --> */}
      <script src="../assets/js/dz.carousel.min.js"></script>
      {/* <!-- OWL-CAROUSEL --> */}
      <script src="../assets/js/dz.ajax.js"></script>
      {/* <!-- AJAX --> */}
      <script src="../assets/js/custom.min.js"></script>
      {/* <!-- CUSTOM JS --> */}
      <script src="../assets/vendor/rangeslider/rangeslider.js"></script>
      <script src="../assets/vendor/switcher/switcher.js"></script>
    </Html>
  )
}
